config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get '/team', to: 'home#team', as: 'team'
  get '/store', to: 'home#store', as: 'store'
  get '/about', to: 'home#about', as: 'about'

  resources :fragments, only: [:index, :show, :destroy]
  
  resources :books do 
    resources :fragments
    resources :words, only: [:index]
  end
  get 'books/:id/tree', to: 'books#tree', as: :tree
  get 'books/:id/add_book_mark', to: 'book_marks#add_from_book', as: :add_book_mark


  resources :book_marks, except: [:show, :new]
  get 'book_marks/:id/box', to: 'book_marks#sandbox', as: :book_marks_box
  get 'book_marks/:id/read', to: 'book_marks#read', as: :read
  
  post '/book_marks/:id/edit_config', to: 'book_marks#update_config', as: :book_marks_update_config

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                     :integer          not null, primary key
#  title                  :string
#  author                 :string
#  age                    :integer
#  format                 :integer          default("bard")
#  config                 :jsonb            not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  description            :text
#  publisher              :text
#  thumbnail_file_name    :string
#  thumbnail_content_type :string
#  thumbnail_file_size    :integer
#  thumbnail_updated_at   :datetime
#  cover_file_name        :string
#  cover_content_type     :string
#  cover_file_size        :integer
#  cover_updated_at       :datetime
#

class Book < ApplicationRecord
  has_many :fragments, dependent: :destroy
  has_many :book_marks, dependent: :destroy
  has_many :words, dependent: :destroy
  has_many :ressources, as: :ressourceable, :dependent => :destroy
  belongs_to :fragment
  
  has_attached_file :thumbnail, default_url: "/images/missing_book_thumbnail.png"
  has_attached_file :cover, default_url: "/images/missing_book.png"
  
  validates_attachment_content_type :thumbnail, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  accepts_nested_attributes_for :ressources, :reject_if => :all_blank, :allow_destroy => true

  enum :format => { :bard => 0, :epub => 1 }
  formats = { :bard => 0, :epub => 1 }



  def dictionnary
    dictionnary = words.map { |w| {id: w.id, name: w.name, match: w.match, url: w.file_url }}.to_json
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :tree]
  before_action :is_admin?, only: [:new, :edit, :create, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    respond_to do |format|
      format.js
      format.json
      format.html
    end
  end

  def tree
    if !@book_mark 
      redirect_to @book, notice: "Vous ne disposez pas de ce livre"
    end
    @fragments = Fragment.where(book: params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      @book_mark = BookMark.find_by({book: @book.id, user: current_user});
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :age, :publisher, :description, :config, :ressources_attributes => [:id, :name, :_destroy, :mode, :file])
    end

    def is_admin?
      if !current_user || !current_user.admin?
        redirect_to root_path, notice: "Vous n'êtes pas autoriser à modifier ces ressources"
      end
    end
end

app/views/books/_form.html.erb
<%= form_for(book, html: { enctype: "multipart/form-data"}) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
    <%= f.label :title %>
  </div>

  <div class="field">
    <%= f.text_field :author %>
    <%= f.label :author %>
  </div>

  <div class="field">
    <%= f.number_field :age %>
    <%= f.label :age, value: "Age minimum" %>
  </div>

  <div class="field">
    <%= f.select :format, Book.formats %>
    <%= f.label :format %>
  </div>

  <div class="field">
    <%= f.text_field :publisher %>
    <%= f.label :publisher %>
  </div>

  <div class="field">
    <%= f.text_field :description %>
    <%= f.label :description %>
  </div>

  <div id="codemirror-block" class="field codemirror">
    <%= f.label :config %>
    <%= f.text_area :config, class: "codemirror__textarea" %>
    <button id="" class="material-icons" data-toggle-target="#codemirror-block" data-toggle-modifier="codemirror--full" >
      fullscreen
    </button>
  </div>


  <div class="ressources" data-namespace="book">
    <div class="field">
      <label for="">Ressources</label>
    </div>
    <div class="ressources__fields">
      <%= f.fields_for :ressources, book.ressources do |fr| %>
        <div class="ressources__field" data-index="<%= fr.index %>">  
  
          <div class="ressources__field-thumbnail">
            <%= image_tag book.ressources[fr.index].file %>
          </div>

          <div class="ressources__field-name">
            <%= fr.text_field :name, placeholder: "Nom du fichier" %>
          </div>

          <div class="ressources__field-file">
            <%= fr.file_field :file %>
          </div>
          <!-- Onclick, pass _destroy to 1  -->
          <%= fr.hidden_field :_destroy, :class => 'removable' %>
          <%= fr.hidden_field :id %>
          <button class="ressources__field-remove"><i class="material-icons">close</i></button>
        </div>
      <% end %>
      <% i = book.ressources.length %>

      <div class="ressources__field ressources__field--added" data-index="<%= i %>">
        <div class="ressources__field-name">
          <input value="" name="book[ressources_attributes][<%= i %>][name]" id="book_ressources_attributes_<%= i %>_name" placeholder="Nom du fichier" type="text">
        </div>
        <div class="ressources__field-file">
          <input name="book[ressources_attributes][<%= i %>][file]" id="book_ressources_attributes_<%= i %>_file" type="file">
        </div>
        <button class="ressources__field-remove">
          <i class="material-icons">close</i>
        </button>
      </div>
    </div>
    <button class="ressources__add btn">Ajouter</button>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container container--small mt-4 mb-5">
  
  <h1 class="title-1 container__title text-center">Editer livre</h1>

  <%= render 'form', book: @book %>

  <div class="text-right">
    <%= link_to 'Show', @book %> |
    <%= link_to 'Back', books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-4">
  
  <h1 class="title-1 container__title">Books</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Age</th>
        <th>Interactive</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.age %></td>
          <td><%= book.format %></td>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path, class: "btn" %>

</div>

app/views/books/new.html.erb
<div class="container mt-4">
  <h1 class="title-1 container__title text-center">Nouveau livre</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div class="book delay-3" data-scrollable data-scrollable-modifier="book--visible" style="background-image: url('<%= @book.cover.url %>')">

  <div class="book__container">
    <div class="container">
      <%= link_to book_marks_path, class: "book__close-btn animate--from-fade-bottom delay-3 smoothout", data: {scrollable: "",  "scrollable-modifier": "animate--launched", "smoothout-modifier": "main--hidden-bottom"} do  %>
      <i class="material-icons">close</i>
      <% end %>
      <h1 class="book__title title-1 container__title animate--from-fade-bottom delay-3" data-scrollable data-scrollable-modifier="animate--launched"><%= @book.title %></h1>
      <div class="book__specs animate--from-fade-bottom delay-2" data-scrollable data-scrollable-modifier="animate--launched">
        <p class="book__spec"><%= @book.author %></p>
        <p class="book__spec">À partir de <%= @book.age %> ans</p>
        <p class="book__spec"><%= @book.publisher %></p>
        <p class="book__spec">Durée: 35min</p>
      </div>
      <div class="book__description animate--from-fade-bottom delay-1" data-scrollable data-scrollable-modifier="animate--launched">
        <%= raw @book.description %>
      </div>
      <div class="book__actions animate--from-fade-bottom" data-scrollable data-scrollable-modifier="animate--launched">
        <% if @book_mark %>
          <%= link_to "Commencez l'aventure", read_path(id: @book), class: "btn btn--slide smoothout",
          data: { "toggle-target": "#header-top-main", "toggle-modifier": "header--slided-top" } %>
        <% else %>
          <%= link_to "Ajouter à ma bibliothèque", add_book_mark_path(id: @book.id), class: "btn btn--slide smoothout" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if current_user && current_user.admin? %>
<div class="adminbar">
  <%= link_to 'Edit', edit_book_path(@book), class: "adminbar__item" %>
  <%= link_to 'Liste de fragments', book_fragments_path(@book), class: "adminbar__item" %>
</div>
<% end %>

app/views/books/tree.html.erb
<%= render "partials/tree", fragments: @fragments %>