config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get '/team', to: 'home#team', as: 'team'
  get '/store', to: 'home#store', as: 'store'
  get '/about', to: 'home#about', as: 'about'

  resources :fragments, only: [:index, :show, :destroy]
  
  resources :books do 
    resources :fragments
    resources :words, only: [:index]
  end
  get 'books/:id/tree', to: 'books#tree', as: :tree
  get 'books/:id/add_book_mark', to: 'book_marks#add_from_book', as: :add_book_mark


  resources :book_marks, except: [:show, :new]
  get 'book_marks/:id/box', to: 'book_marks#sandbox', as: :book_marks_box
  get 'book_marks/:id/read', to: 'book_marks#read', as: :read
  
  post '/book_marks/:id/edit_config', to: 'book_marks#update_config', as: :book_marks_update_config

end

app/models/fragment.rb
# == Schema Information
#
# Table name: fragments
#
#  id                     :integer          not null, primary key
#  name                   :string
#  content                :text
#  config                 :jsonb            not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  book_id                :integer
#  thumbnail_file_name    :string
#  thumbnail_content_type :string
#  thumbnail_file_size    :integer
#  thumbnail_updated_at   :datetime
#

class Fragment < ApplicationRecord
  belongs_to :book
  has_many :ressources, as: :ressourceable, dependent: :destroy
  has_many :fragment_links, :foreign_key => :parent_id, dependent: :destroy
  has_many :children, :through => :fragment_links, :source => :child

  has_attached_file :thumbnail, default_url: "/images/missing_fragment.png"
  validates_attachment_content_type :thumbnail, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  accepts_nested_attributes_for :ressources, :reject_if => :all_blank, :allow_destroy => true

  def js_class
    # I18n.transliterate(@fragment.name.split.map(&:capitalize).join)
    name.parameterize(separator: "_").classify
  end
    
end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController
  before_action :set_fragment, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, except: [:show]
  protect_from_forgery except: :show
  before_action :authenticate_user!

  # GET /fragments
  # GET /fragments.json
  def index
    @fragments = params[:book_id] ? Fragment.where(book: params[:book_id]) : Fragment.all
  end

  # GET /fragments/1
  # GET /fragments/1.json
  def show
    @fragments = Fragment.where(book: @fragment.book)
    @book_mark = BookMark.find_by(book: @fragment.book, user: current_user);

    respond_to do |format|
      format.js
      format.json
      format.html { render "bard", layout: "bard" }
    end
  end

  # GET /fragments/new
  def new
    @fragment = Fragment.new
    @book = Book.find(params[:book_id])
    @fragment.book = @book
  end

  # GET /fragments/1/edit
  def edit
  end

  # POST /fragments
  # POST /fragments.json
  def create
    @fragment = Fragment.new(fragment_params)
    @book = Book.find(params[:book_id])
    respond_to do |format|
      if @fragment.save
        format.html { redirect_to book_fragments_path(book_id: @fragment.book, id: @fragment), notice: 'Fragment was successfully created.' }
        format.json { render :show, status: :created, location: @fragment }
      else
        format.html { render :new }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fragments/1
  # PATCH/PUT /fragments/1.json
  def update
    respond_to do |format|
      if @fragment.update(fragment_params)
        format.html { redirect_to book_fragments_path(book_id: @fragment.book, id: @fragment), notice: 'Fragment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fragment }
      else
        format.html { render :edit }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fragments/1
  # DELETE /fragments/1.json
  def destroy
    @fragment.destroy
    respond_to do |format|
      format.html { redirect_to fragments_url, notice: 'Fragment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fragment
      @fragment = Fragment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fragment_params
      params.require(:fragment).permit(:name, :content, :config, :book_id, :ressources_attributes => [:id, :name, :_destroy, :mode, :file])
    end

    def is_admin?
      if !current_user.admin?
        redirect_to root_path, notice: "Vous n'êtes pas autoriser à modifier ces ressources"
      end
    end
end

app/helpers/fragments_helper.rb
module FragmentsHelper
end

app/views/fragments/_form.html.erb
<%= form_for([book, fragment], html: { enctype: "multipart/form-data"}) do |f| %>
  <% if fragment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fragment.errors.count, "error") %> prohibited this fragment from being saved:</h2>

      <ul>
      <% fragment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :book_id %>

  <div class="field">
    <%= f.text_field :name %>
    <%= f.label :name %>
  </div>


  <div id="codemirror-block" class="field codemirror">
    <%= f.label :content %>
    <%= f.text_area :content, class: "codemirror__textarea" %>
    <button id="" class="material-icons" data-toggle-target="#codemirror-block" data-toggle-modifier="codemirror--full" >
      fullscreen
    </button>
  </div>

  <div id="codemirror-block-2" class="field">
    <%= f.label :config %>
     <%= f.text_area :config, class: "codemirror__textarea" %>
    <button id="" class="material-icons" data-toggle-target="#codemirror-block-2" data-toggle-modifier="codemirror--full" >
      fullscreen
    </button>
  </div>

  <div class="ressources" data-namespace="fragment">
    <div class="field">
      <label for="">Ressources</label>
    </div>
    <div class="ressources__fields">
      <%= f.fields_for :ressources, fragment.ressources do |fr| %>
        <div class="ressources__field" data-index="<%= fr.index %>">  
  
          <div class="ressources__field-thumbnail">
            <%= image_tag fragment.ressources[fr.index].file %>
          </div>

          <div class="ressources__field-name">
            <%= fr.text_field :name, placeholder: "Nom du fichier" %>
          </div>

          <div class="ressources__field-file">
            <%= fr.file_field :file %>
          </div>
          <!-- Onclick, pass _destroy to 1  -->
          <%= fr.hidden_field :_destroy, :class => 'removable' %>
          <%= fr.hidden_field :id %>
          <button class="ressources__field-remove"><i class="material-icons">close</i></button>
        </div>
      <% end %>
      <% i = fragment.ressources.length %>

      <div class="ressources__field ressources__field--added" data-index="<%= i %>">
        <div class="ressources__field-name">
          <input value="" name="fragment[ressources_attributes][<%= i %>][name]" id="fragment_ressources_attributes_<%= i %>_name" placeholder="Nom du fichier" type="text">
        </div>
        <div class="ressources__field-file">
          <input name="fragment[ressources_attributes][<%= i %>][file]" id="fragment_ressources_attributes_<%= i %>_file" type="file">
        </div>
        <button class="ressources__field-remove">
          <i class="material-icons">close</i>
        </button>
      </div>
    </div>
    <button class="ressources__add btn">Ajouter</button>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fragments/bard.html.erb
<div class="fragment">
  <div class="fragment__background"></div>
  <canvas class="fragment__canvas fragment__canvas--hidden" id="bard-canvas" data-book="<%= @fragment.book.id %>"></canvas> 
  <div class="fragment__foreground"></div>
</div>


<div class="loader">
  <%= image_tag "loader.gif", class: "loader__img" %>
</div>

<!-- Menu -->
<div id="controller" class="control control--hide">
  <button id="control-menu-btn" class="control__btn">
  </button>

  <div class="control__out control__out--6">
    <button id="pass-interaction-btn" class="control__btn control__out-item control__out-item--dark">
      <%= image_tag "picto/picto-arrow.svg" %>
      <span class="control__out-item-label">Passer</span>
    </button>
  </div>

  <div class="control__menu">
    <button class="control__btn control__menu-item" data-target="help">
      <%= image_tag "picto/picto-_.svg" %>
    </button>
    <button class="control__btn control__menu-item" data-target="settings">
      <%= image_tag "picto/picto-settings.svg" %>
    </button>
    <button class="control__btn control__menu-item" data-target="arborescence">
      <%= image_tag "picto/picto-boussole.svg" %>
    </button>
    <button class="control__btn control__menu-item" data-target="fullscreen">
      <%= image_tag "picto/picto-fullscreen.svg" %>
    </button>
    <a href="<%= book_path(@fragment.book) %>" class="control__btn control__menu-item" data-target="pause">
      <%= image_tag "picto/picto-sortie.svg" %>
    </a>
  </div>
</div>

<div id="customization-panel" class="customization customization--hidden">
  <h2 class="title-1 text-center">Personnalise ton héros</h2>
  <div class="customization__sidebar customization__sidebar--left">
    <h3 class="customization__sub-title">À quoi ressembles-tu ?</h3>
    <div class="customization__lists">
       <div id="body-part-categories-container" class="customization__list  customization__list--depth-1">
        <button id="csqe" class="customization__list-item"><%= image_tag "personnalisation/asset-head-shield.png" %></button>
        <button id="tete" class="customization__list-item"><%= image_tag "personnalisation/asset-head.png" %></button>
        <button id="crps" class="customization__list-item"><%= image_tag "personnalisation/asset-body.png" %></button>
        <button id="bras" class="customization__list-item"><%= image_tag "personnalisation/asset-arm.png" %></button>
        <button id="jmbe" class="customization__list-item"><%= image_tag "personnalisation/asset-leg.png" %></button>
        <button id="arme" class="customization__list-item"><%= image_tag "personnalisation/asset-arme.png" %></button>
      </div>
      <div id="body-part-choices-container" class="customization__list customization__list--hidden customization__list--depth-2"></div>
    </div>
  </div>

  <div class="customization__sidebar customization__sidebar--right">
    <h3 class="customization__sub-title">De quelle couleur es-tu ?</h3>
    <div class="customization__section customization__colors">
      <button data-color="#1a33e3" id="customization-color-blue" class="customization__color"></button>
      <button data-color="#ffe600" id="customization-color-yellow" class="customization__color"></button>
      <button data-color="#02114a" id="customization-color-dark" class="customization__color"></button>
      <button data-color="#ff8d79" id="customization-color-orange" class="customization__color"></button>
    </div>

    <h3 class="customization__sub-title">Pousse ton cri de guerre</h3>
    <div class="customization__section mb-3">
      <div class="text-center flex-1">
        <button class="customization__recorder customization__recorder--inactive"></button> 
      </div>
      <div class="text-center flex-1 customization__play-container customization__play-container--hidden">
        <button class="customization__play"></button> 
      </div>
    </div>

    <h3 class="customization__sub-title">Quel est ton nom ?</h3>
    <div class="customization__form">
      <p class="customization__mention customization__form-label">Ton titre</p>
      <div class="select">
        <select aria-label="Select menu example" id="title-input">
          <option selected value="1">Chevalier</option>
          <option value="2">Chevalière</option>
          <option value="3">Prince</option>
          <option value="4">Princesse</option>
        </select>
      </div>
      <p class="customization__mention customization__form-label">Ton Nom</p>
      <input type="text" class="customization__form-input" id="name-input">
    </div>
  </div>

  <div class="customization__cta">
    <button id="customization-save" class="btn">Partir à l'aventure</button>
  </div>
</div>



<!-- Tree -->
<div id="arborescence-panel" class="panel panel--hidden">
  <div class="panel__container">
    <button class="panel__close">
      <%= image_tag "picto/picto-erreur.svg" %>
    </button>
    <h2 class="title-1 text-center panel__title"><%= @fragment.book.title %></h2>
    <%= link_to "Ma Boîte Magique", book_marks_box_path(@book_mark), class: "btn btn--slide bottom-center-medium smoothout" %>
  </div>
  <%= render "partials/tree", fragments: @fragments %>
</div>



<!-- Settings -->
<div id="settings-panel" class="panel panel--hidden">
  <div class="panel__container">
    <button class="panel__close"><%= image_tag "picto/picto-erreur.svg" %></button>
    <h2 class="title-1 text-center panel__title">Réglages</h2>
    <div class="settings container">
      
      <div class="settings__item">
        <div class="settings__item-label">
          <%= image_tag "picto/picto-img.svg", class: "settings__item-img" %>
          <p class="settings__item-title">Qualité</p>
        </div>
        <div class="settings__item-input">
          <p class="field">
            <span>Faible</span>
            <input id="quality" type="checkbox">
            <label for="quality"></label>
            <span>Haute</span>
          </p>
        </div>
      </div>

      <div class="settings__item">
        <div class="settings__item-label">
          <%= image_tag "picto/picto-participation.svg", class: "settings__item-img" %>
          <p class="settings__item-title">Participation de l'enfant</p>
        </div>
        <div class="settings__item-input">
          <p class="field">
            <span>Non</span>
            <input id="child-participation" type="checkbox">
            <label for="child-participation"></label>
            <span>Oui</span>
          </p>
        </div>
      </div>

      <div class="settings__item">
        <div class="settings__item-label">
          <%= image_tag "picto/picto-commande-vocale.svg", class: "settings__item-img" %>
          <p class="settings__item-title">Commande vocale</p>
        </div>
        <div class="settings__item-input">
          <p class="field">
            <span>Non</span>
            <input id="speech-recognition" type="checkbox">
            <label for="speech-recognition"></label>
            <span>Oui</span>
          </p>
        </div>
      </div>


      <div class="settings__item">
        <div class="settings__item-label">
          <%= image_tag "picto/picto-volume-son.svg", class: "settings__item-img" %>
          <p class="settings__item-title">Volume du son</p>
        </div>
        <div class="settings__item-input">
          <p><input id="sound-gain" type="range" min="0" max="1" step="0.01" value=""></p>
        </div>
      </div>

    </div>
  </div>
</div>


<div id="help-manager" class="help"></div>

<!-- Help -->
<div id="help-panel" class="panel panel--hidden">
  <button class="panel__close"><%= image_tag "picto/picto-erreur.svg" %></button>
  <div class="panel__container">
    <div class="text-center">
      <h3 id="help-title" class="font-big bold mb-5">Cherche et trouve</h3>
      <p  id="help-content" class="mb-5 font-medium">Trouve l’objet mentionné dans le texte et touche-le  <br>pour faire avancer l’histoire.</p>
      <%= image_tag "picto/picto-aide.svg", id: "help-logo" %>
    </div>
    <div class="text-center mt-3">
        <a href="#" class="btn">Plus d'aide</a>
      </div>
  </div>
</div>

<!-- Words -->
<div id="word-panel" class="word-panel panel panel--hidden">
  <button class="panel__close"
  data-toggle-target="#word-panel" data-toggle-modifier="panel--hidden">
  <%= image_tag "picto/picto-erreur.svg" %>
</button>
  <div class="panel__container">
    <div>
      <video width="300" height="500" id="word-panel-video" class="word-panel__video">
      </video>
    </div>
  </div>
</div>

<script type="text/javascript">

  window.addEventListener("load", function(){
    if( window.book ){

      window.book.dictionnary = <%= raw @fragment.book.dictionnary %>
      window.book.config = <%= raw @book_mark.config.to_json %>
      if(typeof window.book.config === "string") {
        window.book.config = JSON.parse(window.book.config);
      }

      console.log(window.book.config);
      window.book.bookMark = <%= @book_mark.id %>
      loadAsyncScript("/books/<%= @fragment.book.id %>/fragments/<%= @fragment.id %>.js", function(element){
        element.parentNode.removeChild(element);
      });
    }
  })
  
</script>

app/views/fragments/edit.html.erb
<div class="container mt-4">
  
  <h1 class="title-1 container__title text-center">Editing Fragment</h1>

  <%= render 'form', fragment: @fragment, book: @fragment.book %>

  <%= link_to 'Show', @fragment %> |
  <%= link_to 'Back', fragments_path %>

</div>

app/views/fragments/index.html.erb
<div class="container mt-4">
  <h1 class="title-1 container__title">Fragments</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Img</th>
        <th>Name</th>
        <th>Config</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @fragments.each do |fragment| %>
        <tr>
          <td><%= image_tag fragment.thumbnail, class: "img--small" %></td>
          <td><%= fragment.name %></td>
          <td><%= link_to 'Show', fragment %></td>
          <td><%= link_to 'Edit', edit_book_fragment_path(book_id: fragment.book, id: fragment) %></td>
          <td><%= link_to 'Destroy', fragment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
    
</div>

app/views/fragments/new.html.erb
<div class="container mt-4">
  <h1 class="title-1 container__title text-center">New Fragment</h1>

  <%= render 'form', fragment: @fragment, book: @book %>

  <%= link_to 'Back', fragments_path, class: "btn" %>
</div>

app/views/fragments/show.html.erb
<div class="container mt-4" >
  <p>
    <strong>Name:</strong>
    <%= @fragment.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @fragment.content %>
  </p>

  <p>
    <strong>Config:</strong>
    <%= @fragment.config %>
  </p>

  <%= link_to 'Edit', edit_book_fragment_path(book_id: @fragment.book, id: @fragment) %> |
  <%= link_to 'Back', book_fragments_path(@fragment.book) %>

</div>

app/views/fragments/show.js.erb
if( book ) {
  
  var isStarted = book.fragments.length > 0 ? true : false;

  class <%= @fragment.js_class %> extends Bard.Fragment <%= raw @fragment.content %>

  var frag = new <%= @fragment.js_class %>();
  frag.id = <%= @fragment.id %>;
  frag.childrenLinks = <%= raw @fragment.children.map(&:id).to_json %>  
  

  book.addFragment(frag);

  frag.on("start", function(){
    for(var i=0; i<this.childrenLinks.length; i++){
      loadAsyncScript("/books/<%= @fragment.book.id %>/fragments/"+this.childrenLinks[i]+".js", function(element){
        element.parentNode.removeChild(element);
      });
    }
  })


  if( !isStarted ) book.start();

}