config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get '/team', to: 'home#team', as: 'team'
  get '/store', to: 'home#store', as: 'store'
  get '/about', to: 'home#about', as: 'about'

  resources :fragments, only: [:index, :show, :destroy]
  
  resources :books do 
    resources :fragments
    resources :words, only: [:index]
  end
  get 'books/:id/tree', to: 'books#tree', as: :tree
  get 'books/:id/add_book_mark', to: 'book_marks#add_from_book', as: :add_book_mark


  resources :book_marks, except: [:show, :new]
  get 'book_marks/:id/box', to: 'book_marks#sandbox', as: :book_marks_box
  get 'book_marks/:id/read', to: 'book_marks#read', as: :read
  
  post '/book_marks/:id/edit_config', to: 'book_marks#update_config', as: :book_marks_update_config

end

app/models/book_mark.rb
# == Schema Information
#
# Table name: book_marks
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  book_id     :integer
#  config      :jsonb            not null
#  nb_visit    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  fragment_id :integer
#

class BookMark < ApplicationRecord
  belongs_to :user
  belongs_to :book
  belongs_to :fragment
end

app/controllers/book_marks_controller.rb
class BookMarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book_mark, only: [:show, :edit, :update, :destroy, :update_config, :sandbox]  
  
  # GET /book_marks
  def index
    @book_marks = BookMark.where(user: current_user)
    @books_interest = Book.all.except(@book_marks.map(&:book)).first(3)
  end


  def read
    @book = Book.find(params[:id]);
    if !current_user
      redirect_to @book, notice: 'Vous devez être connecté pour lire une histoire.'
    end

    @book_mark = BookMark.find_by(book_id: @book.id, user_id: current_user.id);
    if !@book_mark
      redirect_to @book, notice: 'Vous ne disposez pas de ce livre pour le moment, veuillez l\'ajouter à votre bibliothèque.'
    end

    if !@book_mark.fragment
      if @book_mark.book.fragment
        @book_mark.fragment = @book_mark.book.fragment
      else 
        @book_mark.fragment = @book_mark.book.fragments.first
      end
    end

    redirect_to @book_mark.fragment
  end

  # GET /book_marks/1/box
  def sandbox
    @words = Word.where(book: @book_mark.book)
  end

  # POST /book_marks
  # POST /book_marks.json
  def create
    @book_mark = BookMark.new(book_mark_params)

    respond_to do |format|
      if @book_mark.save
        format.html { redirect_to @book_mark, notice: 'Book mark was successfully created.' }
        format.json { render :show, status: :created, location: @book_mark }
      else
        format.html { render :new }
        format.json { render json: @book_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_marks/1
  # PATCH/PUT /book_marks/1.json
  def update
    respond_to do |format|
      if @book_mark.update(book_mark_params)
        format.html { redirect_to @book_mark, notice: 'Book mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_mark }
      else
        format.html { render :edit }
        format.json { render json: @book_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_config
    if params[:config]
      config = ActiveSupport::JSON.decode(params[:config])

      @book_mark.config["variables"].keys.each do |key|
        @book_mark.config["variables"][key] = config["variables"][key]
      end

      @book_mark.config["character"]["body_parts"].keys.each do |key|
        @book_mark.config["character"]["body_parts"][key] = config["character"]["body_parts"][key]
      end

      @book_mark.save;

      respond_to do |format|
        format.json { render json: config["variables"] }
      end
    end
  end


  def add_from_book
    @book = Book.find(params[:id])
    if @book && current_user
     @book_mark = BookMark.find_by({book: @book, user: current_user}) 
     if !@book_mark
      @book_mark = BookMark.create({book: @book, user: current_user, fragment: @book.fragments.first, config: @book.config})
      if @book.fragment
        @book_mark.fragment = @book.fragment
      end
      @book_mark.save
     end
    end
    redirect_to @book, notice: @book.title.capitalize + ' a bien été rajouté à votre bibliothèque.'
  end 


  # DELETE /book_marks/1
  # DELETE /book_marks/1.json
  def destroy
    @book_mark.destroy
    respond_to do |format|
      format.html { redirect_to book_marks_url, notice: 'Votre livre a bien été supprimé de votre bibliothèque.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_mark
      @book_mark = BookMark.find(params[:id])
      if !@book_mark
        redirect_to root_path, notice: "Aucune référence n'existe vers ce marque-page"
      end

      if @book_mark.user.id != current_user.id && !current_user.admin?
        redirect_to @book_mark.book, notice: "Vous n'êtes pas autorisé"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_mark_params
      params.require(:book_mark).permit(:user_id, :book_id, :config, :nb_visit)
    end
end

app/helpers/book_marks_helper.rb
module BookMarksHelper
  # Rails
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    fallback_path = "#{Rails.root}/app/assets/images/png/#{name}.png"
    return image_tag("png/#{name}.png") if File.exists?(fallback_path)
    '(not found)'
  end

end

app/views/book_marks/_form.html.erb
<%= form_for(book_mark) do |f| %>
  <% if book_mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_mark.errors.count, "error") %> prohibited this book_mark from being saved:</h2>
      <ul>
      <% book_mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="codemirror-block" class="field codemirror">
    <%= f.label :config %>
    <%= f.text_area :config, class: "codemirror__textarea" %>
    <button id="" class="material-icons" data-toggle-target="#codemirror-block" data-toggle-modifier="codemirror--full" >
      fullscreen
    </button>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_marks/edit.html.erb
<div class="container mt-4">
  
  <h1 class="title-1 container__title">Editer Book Mark</h1>

  <%= render 'form', book_mark: @book_mark %>
  
  <div class="text-right">
    <%= link_to 'Show', @book_mark %> |
    <%= link_to 'Back', book_marks_path %>
  </div>
  
</div>

app/views/book_marks/index.html.erb
<div class="container mt-4">

<h1 class="title-1 container__title animate--from-fade-bottom delay-3" data-scrollable data-scrollable-modifier="animate--launched">
  Ma bibliothèque
</h1>

<% if @book_marks.length < 1 %>

<p class="books__empty  animate--from-fade-bottom delay-2" data-scrollable data-scrollable-modifier="animate--launched">Vous n'avez pas encore de livres dans votre bibliothèque.</p> 

<% else %>

<div class="books animate--from-fade-bottom delay-2" data-scrollable data-scrollable-modifier="animate--launched">
  <% @book_marks.each do |book_mark| %>
    <%= link_to book_path(book_mark.book), class: "books__item smoothout" do %>
      <div class="books__item-img-container">
        <img src="<%= book_mark.book.thumbnail.url %>" class="books__item-img" alt="<%= book_mark.book.title %>">  
      </div>
      <p class="books__item-title"><%= book_mark.book.title %></p>
      <p class="books__item-subtitle"><%= book_mark.book.author %></p>
    <% end %>
  <% end %>
</div>

<% end %>

<% if @books_interest.length > 0 %>

<h2 class="title-2 mt-4 container__sub-title animate--from-fade-bottom delay-1" data-scrollable data-scrollable-modifier="animate--launched">Ces livres peuvent également vous intéresser</h2>  

<div class="books animate--from-fade-bottom" data-scrollable data-scrollable-modifier="animate--launched">
  <% @books_interest.each do |book| %>
    <%= link_to book_path(book), class: "books__item books__item--small" do %>
      <div class="books__item-img-container">
        <img src="<%= book.thumbnail.url %>" class="books__item-img" alt="<%= book.title %>">  
      </div>
      <p class="books__item-title"><%= book.title %></p>
      <p class="books__item-subtitle"><%= book.author %></p>
    <% end %>
  <% end %>
</div>
<% end %>

</div>

app/views/book_marks/new.html.erb
<div class="container mt-4">
  <h1 class="title-1 container__title">New Book Mark</h1>

  <%= render 'form', book_mark: @book_mark %>
  
  <div class="text-right">
    <%= link_to 'Back', book_marks_path %>  
  </div>
</div>

app/views/book_marks/sandbox.erb
<section id="sandbox" class="sandbox bard">
  <canvas class="sandbox__canvas"></canvas>

  <!-- Alphabet -->
  <div class="alphabet__input">
    <svg id="alphabet__sandbox" viewBox="0 0 1920 1280"></svg>
  </div>
  <div class="alphabet__storage">
    <%  ("A".."Z").each do |letter| %>
      <%= svg("typo/"+letter) %>
    <% end %>
  </div>

  <!-- Dialog -->
  <div id="dialog-1" class="dialog">
    <p class="dialog__content">
      <span class="bold block mb-2">Bienvenue dans ta boîte magique !
      <br>Prononce ou écris un mot magique
      <br>pour le faire apparaître.</span>
      <span class="italic">Exemple : Fusée</span>
    </p>
    <span class="btn btn--slide mt-3" data-toggle-target="#dialog-1, #dialog-2" data-toggle-modifier="dialog--hidden, dialog--hidden">J'ai compris</span>
  </div>

  <div id="dialog-2" class="dialog dialog--hidden">
    <p class="dialog__content">
      <span class="bold block">
        Tu peux retrouver ta collection de mots magiques<br>
        en cliquant sur l'icône<br>
        en bas à droite.
      </span>
    </p> 
    <span class="btn btn--slide mt-3" data-toggle-target="#dialog-2, #controller" data-toggle-modifier="dialog--hidden, control--disabled">J'ai compris</span>
  </div>


  <!-- Menu -->
<div id="controller" class="control control--hide control--disabled">
  <button id="control-menu-btn" class="control__btn" data-toggle-target="#controller" data-toggle-modifier="control--hide">
  </button>

  <div class="control__out control__out--4">
    <button class="control__btn control__out-item" data-toggle-target="#dictionnary-box" data-toggle-modifier="panel--hidden">
      <%= image_tag "picto/picto-mots-magiques.svg" %>
      <span class="control__out-item-label">Mes mots<br>magique</span>
    </button>
  </div>

  <div class="control__menu control__menu--3">
    <button class="control__btn control__menu-item" data-toggle-target="#arborescence-panel" data-toggle-modifier="panel--hidden">
      <%= image_tag "picto/picto-boussole.svg" %>
    </button>
    <button class="control__btn control__menu-item" data-target="fullscreen">
      <%= image_tag "picto/picto-fullscreen.svg" %>
    </button>
    <a href="<%= book_path(@book_mark.book) %>" class="control__btn control__menu-item" data-target="pause">
      <%= image_tag "picto/picto-sortie.svg" %>
    </a>
  </div>
</div>


<!-- Tree -->
<div id="arborescence-panel" class="panel panel--hidden">
  <div class="panel__container">
    <button class="panel__close" data-toggle-target="#arborescence-panel" data-toggle-modifier="panel--hidden"><%= image_tag "picto/picto-erreur.svg" %></button>
    <h2 class="title-1 text-center panel__title"><%= @book_mark.book.title %></h2>
    <a href="" class="btn bottom-center-big">Ma collection de mot</a>
  </div>
  <%= render "partials/tree", fragments: @book_mark.book.fragments %>
</div>


<!-- Dictionnary  -->
<div id="dictionnary-box" class="panel panel--hidden panel--no-flex">
  <div class="panel__container mb-5">
    <button class="panel__close" data-toggle-target="#dictionnary-box" data-toggle-modifier="panel--hidden"><%= image_tag "picto/picto-erreur.svg" %></button>
    <h2 class="title-1 text-center panel__title">Mes mots magiques</h2>
  </div>
  
  <div id="dictionnary-storage" class="dictionnary__storage">
    <%= @words.map { |word| { name: word.name, path: word.thumbnail.url,  config: word.config }}.to_json.html_safe %>
  </div>

  <div class="flex flex--between container mb-5">
    <% @words.each do |word| %>
      <div class="magicword dictionnary__list-item">
        <%= image_tag word.thumbnail.url, class: "magicword__img" %>
        <p class="magicword__title"><%= word.name %></p>

        <ul class="magicword__synonymes">
          <% word.config["synonymous"].each do |synonym| %>
          <li class="magicword__synonyme"><%= synonym.capitalize %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

</section>

app/views/book_marks/show.html.erb
<div class="container mt-4">
  <p>
    <strong>User:</strong>
    <%= @book_mark.user %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= @book_mark.book %>
  </p>

  <p>
    <strong>Config:</strong>
    <%= @book_mark.config %>
  </p>

  <p>
    <strong>Nb visit:</strong>
    <%= @book_mark.nb_visit %>
  </p>

  <div class="text-right">
    <%= link_to 'Edit', edit_book_mark_path(@book_mark) %> |
    <%= link_to 'Back', book_marks_path %>
  </div>

</div>