config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  get '/team', to: 'home#team', as: 'team'
  get '/store', to: 'home#store', as: 'store'
  get '/about', to: 'home#about', as: 'about'

  resources :fragments, only: [:index, :show, :destroy]
  
  resources :books do 
    resources :fragments
    resources :words, only: [:index]
  end
  get 'books/:id/tree', to: 'books#tree', as: :tree
  get 'books/:id/add_book_mark', to: 'book_marks#add_from_book', as: :add_book_mark


  resources :book_marks, except: [:show, :new]
  get 'book_marks/:id/box', to: 'book_marks#sandbox', as: :book_marks_box
  get 'book_marks/:id/read', to: 'book_marks#read', as: :read
  
  post '/book_marks/:id/edit_config', to: 'book_marks#update_config', as: :book_marks_update_config

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spell</title>
    <%= csrf_meta_tags %>
    
    <%= javascript_pack_tag 'application' %>
    <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header id="header-top-main" class="header header--wheel-sensitive">
      <div class="container">
        <nav class="header__nav header__nav--left">
          <%= link_to root_path, class: "smoothout" do %>
          <h1 class="header__brand header__brand--left">
            <%= image_tag "logo-horizontal.svg" %>
          </h1>
          <% end %>
        </nav>
      
        <nav class="header__nav header__nav--right">
          <ul class="header__menu">
            <li class="header__menu-item">
              <%= link_to "Ma Bibliothèque", book_marks_path, class: "smoothout" %>
            </li>
            <li class="header__menu-item">
              <a href="#" class="header__drop-btn">Mon Compte</a>
              <div class="header__drop header__drop--close">
                <%= link_to "Paramètres du compte", edit_user_registration_path, class: "header__drop-item smoothout" %>
                <%= link_to "Déconnexion", destroy_user_session_path, :method => "delete", class: "header__drop-item smoothout" %>
              </div>
            </li>
          </ul>
        </nav>
      </div>
  </header>

  <div class="notifications">
    <% if notice %>
    <p class="notification"><%= notice %></p>
    <% end %>
  </div>
    
  <main class="main">
    <%= yield %>  
  </main>
  
  
  </body>
</html>

app/views/layouts/bard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spell</title>
    <%= csrf_meta_tags %>
    
    <%= javascript_pack_tag 'application' %>
    <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="no-pad">

  <div class="notifications">
    <% if notice %>
    <p class="notification"><%= notice %></p>
    <% end %>
  </div>
    
  <div class="bard main">
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spell</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="home-body">
    <header id="header-top-bard" class="header header--wheel-sensitive">
      <div class="container">
         <nav class="header__nav header__nav--left">
          <h1 class="header__brand header__brand--center">
          <%= link_to root_path, class: "smoothout" do %>
            <%= image_tag "logo-horizontal.svg" %>
          <% end %>
          </h1>

          <ul class="header__menu">
            <li class="header__menu-item">
              <%= link_to "À propos", about_path, class: "smoothout"  %>
            </li>
            <li class="header__menu-item">
              <%= link_to "L'équipe", team_path, class: "smoothout"  %>
            </li>
            <li class="header__menu-item">
              <%= link_to "Le Magasin", root_path, class: "smoothout"  %>
            </li>
          </ul>
        </nav>

        <nav class="header__nav header__nav--right">
          
          <ul class="header__menu">
            
            <% if current_user.nil? %>

              <li class="header__menu-item">
                <%= link_to "Connexion", new_user_session_path, class: "smoothout" %>
              </li>
              <li class="header__menu-item">
                <%= link_to "Inscription", new_user_registration_path, class: "smoothout" %>
              </li>

            <% else %>

              <nav class="header__nav header__nav--right">
                <ul class="header__menu">
                  <li class="header__menu-item">
                    <%= link_to "Ma Bibliothèque", book_marks_path, class: "smoothout" %>
                  </li>
                  <li class="header__menu-item">
                    <a href="#" class="header__drop-btn">Mon Compte</a>
                    <div class="header__drop header__drop--close">
                      <%= link_to "Paramètres du compte", edit_user_registration_path, class: "header__drop-item smoothout" %>
                      <%= link_to "Déconnexion", destroy_user_session_path, :method => "delete", class: "header__drop-item smoothout" %>
                    </div>
                  </li>
                </ul>
              </nav>
              
            <% end %>

          </ul>
          
        </nav>       
      </div>
  </header>

  <div class="notifications">
    <% if notice %>
    <p class="notification"><%= notice %></p>
    <% end %>
  </div>
  
  <main class="main">
    <%= yield %>
  </main>

  </body>
</html>